name: h3-py

channels:
  - esri
  - conda-forge

dependencies:
  - arcgis=1.8.1
  - cookiecutter  
  - dask
  - h3-py
  - mkdocs
  - nodejs
  - pip
  - pytest
  - python-dotenv
  - scipy
  - scikit-learn
  - seaborn
  - shapely
  - swifter
  - tqdm
  - pip:
    - azure-storage-blob
    - ipykernel
    - sphinx
    - sphinx-autodoc-typehints
    - sphinx_rtd_theme

  